SELECT* from car_details.car_data;
/*question 1: ADD CHECK CONSTRAINST FOR KILOMETER DRIVEN PROBLEM STATEMENT ENSURE THE KM_DRIVEN COLUMN  ONLY ALLOWS NON_NEGATIVE VALUES.*/
ALTER TABLE car_details.car_data
ADD CONSTRAINT CHECK_km_driven CHECK(km_driven >= 0);
SELECT km_driven from car_details.car_data;

/*QUESTION 2 : ADD A UNIQUE CONSTRAINT PROBLEM STATEMENT : ADD A UNIQURE CONSTRAINT TO A NAME COLUMN TO ENSURE NO DUPLICATE CAR NAMEs*/
SELECT name, COUNT(*) AS duplicate_count_name
FROM car_details.car_data
GROUP BY name
HAVING duplicate_count_name > 1;

SELECT * FROM car_details.car_data 
WHERE name IS NULL;

SET SQL_SAFE_UPDATES = 0;
UPDATE car_details.car_data 
SET name ='placeholder_name'
WHERE name IS NULL;

DELETE FROM car_details.car_data WHERE name IS NULL;
/*ALTER TABLE car_details.car_data
ADD UNIQUE (name(255));*/
SELECT * FROM car_details.car_data;

/*QUESTION 3: MODIFY THE COLUMN PROBLEM STATEMENT :- INCREASE THE SIZE OF THE FUEL COLUMN TO ACCOMODATE LARGER DESCRIPTION*/
ALTER TABLE car_details.car_data
MODIFY COLUMN fuel VARCHAR(150); /*use for the fuel column space*/
SELECT * FROM car_details.car_data;

/*QUESTION 4 : ADD A CHECK CONSTRAINT PROBLEM STATEMENT:- ENSURE THE YEAR IS NOT EARLIER THEN 1900 USING A CHECK CONSTRAINT*/
ALTER TABLE car_details.car_data
ADD CONSTRAINT Check_year CHECK (YEAR >= 1900);

/*QUESTION 5 : DROP A CONSTRAINT PROBLEM STATEMENT : REMOVE THE UNIQUE CONSTRAINT FROM THE NAME COLUMN*/
ALTER TABLE car_details.car_data
DROP INDEX Column_name;
SHOW INDEX FROM car_details.car_data;


/*QUESTION 6 : - RENAME A COLUMN PROBLEM STATEMENT : - RENAME THE OWNER COLUMN TO OWNERSHIP*/
ALTER TABLE car_details.car_data
RENAME COLUMN owner TO ownership;
SELECT *
FROM car_details.car_data;

/*QUESTION 7 :  ADD A NEW COLUMN PROBLEM STATEMENT : - ADD A NEW COLUMN REGISTRATION_STATE TO STAORE THE STATE WHERE THE CAR IS REGISTERED*/
ALTER TABLE car_details.car_data
ADD COLUMN REGISTRATION_STATE VARCHAR(50);
SELECT *
FROM car_details.car_data;

/*QUESTION 8: DROP A COLUMN PROBLEM STATEMENT:- REMOVE THE SELLER TYPE COLUMN*/
ALTER TABLE car_details.car_data
DROP COLUMN seller_type;
SELECT *
FROM car_details.car_data;

/*QUESTION 9: SET A DEFAULT VALUE PROLEM STATEMENT :- SET A DEFAULT VALUE FOR THE FUEL COLUMN AS PETROL*/
ALTER TABLE car_details.car_data
ALTER COLUMN fuel SET DEFAULT 'Petrol';
SELECT *
FROM car_details.car_data;

/*QUESTION 10 : - CHANGE TABLE NAME PROBLEM STATEMENT:- RENAME THE CAR DETAILS TABLE TO VEHICLE DETAILS*/
ALTER TABLE car_details.car_data
RENAME TO VehicleDetails;
SELECT *FROM VehicleDetails;


